kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

    sidecar:
      dashboards:
        enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 50Mi

  prometheus:
    prometheusSpec:
      # drop retention to 3 days only. 
      retention: 3d

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi

  kubeStateMetrics:
    resources:
      requests:
        cpu: 10m
        memory: 32mi
      limits:
        cpu: 50m
        memory: 64Mi

  prometheusOperator:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
